import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'offline_id', type: 'string', isIndexed: true },
        { name: 'server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'customer_number', type: 'string', isOptional: true, isIndexed: true },
        { name: 'customer_name', type: 'string', isOptional: true },
        { name: 'commission', type: 'number', isOptional: true },
        { name: 'balance_after', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'sync_attempts', type: 'number', isOptional: true },
        { name: 'last_sync_attempt', type: 'number', isOptional: true },
        { name: 'sync_error', type: 'string', isOptional: true },
        { name: 'version', type: 'number', isIndexed: true },
        { name: 'device_id', type: 'string', isIndexed: true },
        { name: 'app_version', type: 'string' },
        { name: 'merchant_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'location_lat', type: 'number', isOptional: true },
        { name: 'location_lng', type: 'number', isOptional: true },
        { name: 'transaction_hash', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'merchants',
      columns: [
        { name: 'offline_id', type: 'string', isIndexed: true },
        { name: 'server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'business_name', type: 'string' },
        { name: 'business_type', type: 'string' },
        { name: 'registration_number', type: 'string', isOptional: true },
        { name: 'tax_id', type: 'string', isOptional: true },
        { name: 'address_street', type: 'string', isOptional: true },
        { name: 'address_city', type: 'string', isOptional: true },
        { name: 'address_region', type: 'string', isOptional: true },
        { name: 'address_country', type: 'string', isOptional: true },
        { name: 'address_postal_code', type: 'string', isOptional: true },
        { name: 'contact_phone', type: 'string', isOptional: true },
        { name: 'contact_email', type: 'string', isOptional: true },
        { name: 'contact_website', type: 'string', isOptional: true },
        { name: 'is_verified', type: 'boolean', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'version', type: 'number', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'operation', type: 'string', isIndexed: true },
        { name: 'table_name', type: 'string', isIndexed: true },
        { name: 'record_id', type: 'string', isIndexed: true },
        { name: 'data', type: 'string' }, // JSON string
        { name: 'priority', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'retry_count', type: 'number', isOptional: true },
        { name: 'last_attempt', type: 'number', isOptional: true },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'batch_id', type: 'string', isOptional: true, isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'users',
      columns: [
        { name: 'offline_id', type: 'string', isIndexed: true },
        { name: 'server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'phone_number', type: 'string', isIndexed: true },
        { name: 'country_code', type: 'string' },
        { name: 'business_name', type: 'string', isOptional: true },
        { name: 'agent_number', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'kyc_status', type: 'string', isIndexed: true },
        { name: 'is_email_verified', type: 'boolean', isOptional: true },
        { name: 'is_phone_verified', type: 'boolean', isOptional: true },
        { name: 'last_login_at', type: 'number', isOptional: true },
        { name: 'login_count', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'version', type: 'number', isIndexed: true },
      ],
    }),
  ],
});